### PR TITLE
fixes #353

### LINKED ISSUE #353: STDIN.noecho error
When asking the user for a session password, Origen crashes

```
Please enter your password:

COMPLETE CALL STACK
-------------------
undefined method `noecho' for #<IO:<STDIN>>
/home/priyavadan/.origen/gems/ruby/2.3.0/gems/origen-0.52.4/lib/origen/users/user.rb:200:in `password'
```

Possible solution here:  https://stackoverflow.com/questions/9324697/why-cannot-use-instance-method-noecho-of-class-io

will submit a PR with the fix.

### PR DESCRIPTION
**Pull request by priyavadan**
fixes #353 

I also added some code that checks if a different user_id is defined in the site config in the user directory. Running into issues where the Linux Subsystem in windows 10 uses a different user id than the corporate ID. If there is another way to change this, I am open to discussing.

### CODE REVIEW

File: spec/user_spec.rb [hunk 1]
```diff
@@ -52,4 +52,14 @@
     Origen.current_user.id.should == original_user.id
     Origen.current_user.id.should_not == 'crradm'
   end
+
+  it 'Checks if a different user id is specified in Origen Site Config' do
```
Comment (pderouen) [inline spec/user_spec.rb]: Does this perform any tests? I only see assignment operators.

**Comment by ginty** [comment]
Not sure about the use of the site-level config to do what is essentially user-level configuration.

Why not just add something like:  `User.current.override_user_id("blah")`

**Comment by ginty** [comment]
I guess I can see the advantage of the site_config over a user model API because you can set it in one location to apply to all your apps, so I can see why you went that way.

I think a env variable is the way to go actually, it is already supported for the user name and email, maybe an additional one is required to override the ID - https://origen-sdk.org/origen//guides/starting/commit/?highlight=ORIGEN_EMAIL#Setting_Your_Name_and_Email

**Comment by priyavadan** [comment]
@ginty updated per our discussion. I'll add some documentation updates for it later today... thanks!
