### PR TITLE
Spec-ing the Collector

### LINKED ISSUE #261: origen test fails is user specifies where to install gems
~~~ruby
  7) Origen.site_config Site config install directories with ENV variables set with ORIGEN_GEM_INSTALL_DIR set uses the value in ORIGEN_GEM_INSTALL_DIR instead of :gem_install_dir
     Failure/Error: expect(Origen.site_config.user_gem_dir).to eql("/env/gem/.origen/gems")
     
       expected: "/env/gem/.origen/gems"
            got: "/users/user/origen/.origen/gems"
     
       (compared using eql?)
     # ./spec/site_config_spec.rb:243:in `block (4 levels) in <top (required)>'
     # ./config/commands.rb:42:in `<top (required)>'
     # ./lib/origen/commands.rb:185:in `require'
     # ./lib/origen/commands.rb:185:in `<top (required)>'
~~~

When travis runs the same build it passes.

### PR DESCRIPTION
**Pull request by coreyeng**
Hi. I've been using the Collector (utility to transform a block into a hash) in more and more features, and I felt the need to properly spec and document it just so its officially part of Origen. That is most of what this PR is.

The basics of the collector are unchanged. All existing specs still pass. A few changes I made were deprecating the <code>store</code> method (it still works, but prints a deprecation warning) in favor the more Ruby-centric <code>to_h</code> and <code>to_hash</code> methods. The collector will also fail if more than one argument is given. Before, any extras would be ignored so I think its more transparent to just fail instead of dropping off parts of the value. Lastly, the collector supports auto-merging now allowing for one-liners to merge an options hash and options block. These are all documented and have accompanying specs tests. Per #262, which was just me not looking closely enough at what the register specs were doing, I've left empty method as setting <code>nil</code> value.

In addition, I added Nokogiri to the gemspec for #259 and added clearing all ENV variables along with the site config when running the site config spec, which I think will fix #261.

Thanks,

Corey

### CODE REVIEW

File: lib/origen/utility/collector.rb [hunk 1]
```diff
@@ -1,14 +1,78 @@
...
+
+        if block_given?
+          yield self
+        end
+      end
+
+      # Legacy store method.
+      def store
+        Origen.log.deprecate 'Collector::store method was used. Please use the Ruby-centric Collector::to_h or Collector::to_hash method instead' \
+                             " Called from: #{caller[0]}"
```
Comment (ginty) [inline lib/origen/utility/collector.rb]: I think if you call `Origen.deprecate` instead of the direct log method, it should report the caller for you like this, just FYI

Comment (coreyeng) [reply lib/origen/utility/collector.rb]: Thanks! I'll use this next time. I didn't know the Origen module had that method as well.
